### ISSUE TITLE
lights will not turn off it lcz

### ISSUE THREAD

**Issue by edellenburg** [galaxy119/SCP-575#4]
I tried to get lights off in LCZ but it seem like no matter what i put in config the lights stayed on in lcz

**Comment by galaxy119** [comment]
LCZ blackouts were disabled completely because they were breaking servers.

As long as you are updated to SMOD 3.3.0+, you can use the newest release https://github.com/galaxy119/SCP-575/releases
and in your config set

575_toggle_lcz: true - Will make Toggled 575 blackouts affect LCZ.
575_timed_lcz: true - Will make Timed 575 blackouts affect LCZ.


A full list of commands and Configs will be posted on the main page within the next day or two, but here they are simplified: 
`575_ranks - A list of server rols able to run scp-575 commands (Default: owner, admin, mod)
575_timed - True/false, if the timed events should be enabled or not (Default: true)
575_delay - The time in seconds before the first timed blackout each round (Default: 540)
575_duration - The time in seconds each blackout lasts (Default: 90)
575_wait - The time between subsequent blackouts (Default: 300)
575_announce - If CASSIE should announce blackout events (Default: true)
575_toggle_lcz - If manually toggled blackouts should affect LCZ (Default: true)
575_timed_lcz - if timed blackouts should affect LCZ (Default: false)`

Commands:
`575 toggle - toggles manual blackouts on/off
575 enable - Enables timed blackout events (if they are disabled)
575 disable - Disables timed blackout events (if they are enabled)`
